name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  tests:
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
    name: tests (php ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run tests
      run: composer test

  linter:
    name: linter-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run linter
      env:
        PHP_CS_FIXER_IGNORE_ENV: 1
      run: composer lint
